id: P1E3B8852
initial_creation_type: input
source_metadata:
  title: Various works from the Shangpa Kagyü tradition
  parent: 3. Various collections
  source: https://sakyalibrary.com
  bases:
    9bfa:
      title: རྨི་ལམ་འཛིན་ལུགས།
      author: ''
      base_file: 9bfa.txt
      order: 1
    eb0f:
      title: སངས་རྒྱས་སྐུ་གསུམ་གྱི་མཛད་པ།
      author: ''
      base_file: eb0f.txt
      order: 2
    df14:
      title: ཡེ་ཤེས་ཀྱི་མཁའ་འགྲོ་མ་ནི་གུ་མའི་རྣམ་ཐར།
      author: ''
      base_file: df14.txt
      order: 3
    63a6:
      title: བཙུན་པ་བསོད་ནམས་བཟང་པོས་མཛད་པའི་སྣར་ཐང་པའི་ལུགས་ཀྱི་ཆོས་སྤྱོད་ནར་མ།
      author: ''
      base_file: 63a6.txt
      order: 4
    f87e:
      title: མཆིམས་ཀྱིས་མཛད་པའི་ཉིན་ཞག་ཕྲུགས་གཅིག་གི་བྱ་བའི་རིམ་པ་བཞུགས་སོ།།
      author: ''
      base_file: f87e.txt
      order: 5
created_at: '2022-04-06T17:56:45.104743'
last_modified_at: '2022-04-06T17:56:45.104749'
